### ISSUE TITLE
イククル例外対応

### ISSUE THREAD

**Issue by tsu-nera** [peach-hack/auto-matching-reiwa#54]
http://galleria-pc:4440/project/auto-matching/execution/show/182
```

20:09:27 | 2020-01-11 20:09:27 [scrapy.spidermiddlewares.httperror] INFO: Ignoring response <403 https://sp.194964.com/bbs/show_bbs.html?q=TTVzV090eEJFdG42aEc3ZnYzeitXZz09>: HTTP status code is not handled or not allowed
-- | --
20:10:12 | 2020-01-11 20:10:12 [scrapy.core.scraper] ERROR: Spider error processing <GET https://sp.194964.com/bbs/show_bbs.html?q=MjYybk9PWmN4R0dEU0FRZzhEbTBVUHNVbDBQQ1FrYnh4UEMrZU5INCs2VTNpTWpoc09FUUVyRUxzSGxXUnI2dA%3D%3D> (referer: https://sp.194964.com/bbs/show_bbs.html?q=dmdGTFc5TGVFQzRNRmlFNUZjODR6ekVZNm9tMUwwZHJsbTlrZHhRTFBQTkZxbjB4Yjc3aEFQbTd5Z1dwQzRvZQ%3D%3D)
20:10:12 | Traceback (most recent call last):
20:10:12 | File "/home/tsu-nera/miniconda3/envs/auto-matching/lib/python3.7/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
20:10:12 | yield next(it)
20:10:12 | File "/home/tsu-nera/miniconda3/envs/auto-matching/lib/python3.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
20:10:12 | for x in result:
20:10:12 | File "/home/tsu-nera/miniconda3/envs/auto-matching/lib/python3.7/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
20:10:12 | return (_set_referer(r) for r in result or ())
20:10:12 | File "/home/tsu-nera/miniconda3/envs/auto-matching/lib/python3.7/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
20:10:12 | return (r for r in result or () if _filter(r))
20:10:12 | File "/home/tsu-nera/miniconda3/envs/auto-matching/lib/python3.7/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
20:10:12 | return (r for r in result or () if _filter(r))
20:10:12 | File "/home/tsu-nera/repo/auto-matching-reiwa/engine/spiders/ikukuru.py", line 145, in parse_board
20:10:12 | next_url = "https://sp.194964.com/bbs/show_bbs.html" + partial_url  # noqa
20:10:12 | TypeError: can only concatenate str (not "NoneType") to str
20:10:25 | 2020-01-11 20:10:25 [scrapy.core.scraper] ERROR: Spider error processing <GET https://sp.194964.com/bbs/show_bbs.html?q=ZGR1S0ZKR1Y5WEtqV2luaDQ0Y1R5SUFJbEh2Mk0vN21GN2p3L0pBclFxOUNaRWZub0oyVWVEek4zOURGODc0ZQ%3D%3D> (referer: https://sp.194964.com/bbs/show_bbs.html?q=VHU5ZE13OWs4RkxCcXl2Vnh2eHlZVzZ6cjdjSnZaR2cvOVVVb0Z2WjVTY1FwNGdQN1liRk5qSHR3NWZod29FYQ%3D%3D)
20:10:25 | Traceback (most recent call last):
20:10:25 | File "/home/tsu-nera/miniconda3/envs/auto-matching/lib/python3.7/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
20:10:25 | yield next(it)
20:10:25 | File "/home/tsu-nera/miniconda3/envs/auto-matching/lib/python3.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
20:10:25 | for x in result:
20:10:25 | File "/home/tsu-nera/miniconda3/envs/auto-matching/lib/python3.7/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
20:10:25 | return (_set_referer(r) for r in result or ())
20:10:25 | File "/home/tsu-nera/miniconda3/envs/auto-matching/lib/python3.7/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
20:10:25 | return (r for r in result or () if _filter(r))
20:10:25 | File "/home/tsu-nera/miniconda3/envs/auto-matching/lib/python3.7/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
20:10:25 | return (r for r in result or () if _filter(r))
20:10:25 | File "/home/tsu-nera/repo/auto-matching-reiwa/engine/spiders/ikukuru.py", line 145, in parse_board
20:10:25 | next_url = "https://sp.194964.com/bbs/show_bbs.html" + partial_url  # noqa
20:10:25 | TypeError: can only concatenate str (not "NoneType") to str


```

**Comment by tsu-nera** [comment]
再現しないので様子見
