### ISSUE TITLE
ワクワク例外対応

### ISSUE THREAD

**Issue by tsu-nera** [peach-hack/auto-matching-reiwa#55]
http://galleria-pc:4440/project/auto-matching/execution/show/182

```
20:06:21 | 2020-01-11 20:06:21 [scrapy.core.scraper] ERROR: Spider error processing <GET https://550909.com/m/bbs/list?genre=3&p=5> (referer: https://550909.com/m/bbs/list?genre=3&p=4)
-- | --
20:06:21 | Traceback (most recent call last):
20:06:21 | File "/home/tsu-nera/miniconda3/envs/auto-matching/lib/python3.7/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
20:06:21 | yield next(it)
20:06:21 | File "/home/tsu-nera/miniconda3/envs/auto-matching/lib/python3.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
20:06:21 | for x in result:
20:06:21 | File "/home/tsu-nera/miniconda3/envs/auto-matching/lib/python3.7/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
20:06:21 | return (_set_referer(r) for r in result or ())
20:06:21 | File "/home/tsu-nera/miniconda3/envs/auto-matching/lib/python3.7/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
20:06:21 | return (r for r in result or () if _filter(r))
20:06:21 | File "/home/tsu-nera/miniconda3/envs/auto-matching/lib/python3.7/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
20:06:21 | return (r for r in result or () if _filter(r))
20:06:21 | File "/home/tsu-nera/repo/auto-matching-reiwa/engine/spiders/wakuwaku.py", line 90, in parse_board
20:06:21 | 'p.profile__name::text').extract_first().strip()
20:06:21 | AttributeError: 'NoneType' object has no attribute 'strip'
20:06:21 | 2020-01-11 20:06:21 [scrapy.core.engine] INFO: Closing spider (finished)
20:06:21 | 2020-01-11 20:06:21 [scrapy.statscollectors] INFO: Dumping Scrapy stats:


```

**Comment by tsu-nera** [comment]
へんな絵文字が原因
